### ISSUE TITLE
Problems creating Asset

### ISSUE THREAD

**Issue by mobius127** [Azure/azure-sdk-for-media-services#189]
Hi, 
Two days ago, my web job took this error when it tried to create an asset, and then provoke encoding workflow error.

Video Name is this: "2.Posesión 4x4+2.mp4"

17:00:02.375 [32] ERROR AnalysisDepartment.AzureMediaServices.Services.MediaService - [ERROR] with Message:    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.WindowsAzure.MediaServices.Client.AssetFileCollection.Create(String name)
   at AnalysisDepartment.AzureMediaServices.Services.MediaService.CopyFileToMediaService(VideoModel video, String fileName)
17:12:26.501 [27] ERROR AnalysisDepartment.AzureMediaServices.Services.MediaService - [ERROR] with Message:    at System.Data.Services.Client.DataServiceRequest.Execute[TElement](DataServiceContext context, QueryComponents queryComponents)
   at System.Data.Services.Client.DataServiceQuery`1.Execute()
   at System.Data.Services.Client.DataServiceQuery`1.GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at System.Data.Services.Client.DataServiceQueryProvider.ReturnSingleton[TElement](Expression expression)
   at System.Data.Services.Client.DataServiceQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.WindowsAzure.MediaServices.Client.MediaQueryProvider`1.<>c__DisplayClass5_0`1.<Execute>b__0()
   at Microsoft.WindowsAzure.MediaServices.Client.TransientFaultHandling.MediaRetryPolicy.ExecuteAction[TResult](Func`1 func)
   at Microsoft.WindowsAzure.MediaServices.Client.MediaQueryProvider`1.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
   at AnalysisDepartment.AzureMediaServices.Services.MediaService.EncodeAndPublishFile(VideoModel video, String assetId)

**Comment by xpouyat** [comment]
Hello Javier,

Your file name has two issues:
-	2 dots in the name
-	And character ‘+’

See https://docs.microsoft.com/en-us/azure/media-services/media-services-rest-upload-files

**Comment by johndeu** [comment]
Closing this issue as a naming issue.
